### ISSUE TITLE
Test Ticket

### ISSUE THREAD

**Issue by valentinajemuovic** [alptium/tamara.jovanovic#1]
Hi @tasajovanovic,

Please do the following:

1. Write a comment below that you have received this test ticket.
2. Please tag me using @ then typing my GitHub name.
3. Then close this ticket.

Thanks,
Valentina

**Comment by tasajovanovic** [comment]
@valentinacupac  hi!

**Comment by valentinajemuovic** [comment]
Thanks @tasajovanovic, you can now close the ticket.
