### ISSUE TITLE
Hello World

### ISSUE THREAD

**Issue by tasajovanovic** [alptium/tamara.jovanovic#2]

**Comment by tasajovanovic** [comment]
@valentinacupac you can review this task.

**Comment by valentinajemuovic** [comment]
@tasajovanovic, it's correct but from style perspective see https://github.com/alptium/valentina.cupac/wiki/03.-Hello-World comment 14, since you had double blank line on lines 4 & 5.

**Comment by tasajovanovic** [comment]
@valentinacupac you can check it now.

**Comment by valentinajemuovic** [comment]
@tasajovanovic, correct.
