### ISSUE TITLE
Calculator

### ISSUE THREAD

**Issue by tasajovanovic** [alptium/tamara.jovanovic#3]

**Comment by tasajovanovic** [comment]
@valentinacupac I've done my task you can check it now.

**Comment by valentinacupac** [comment]
@tasajovanovic, see review comment https://github.com/alptium/valentina.cupac/wiki/03.-Hello-World, comment 14.

**Comment by valentinajemuovic** [comment]
See https://github.com/alptium/valentina.cupac/wiki/03.-Hello-World, comment 29.

**Comment by tasajovanovic** [comment]
@valentinacupac you can check it now.

**Comment by valentinajemuovic** [comment]
@tasajovanovic, correct.
